### PR TITLE
Improve performance of stats calculation

### PR DESCRIPTION
**Pull request by Jobarion**

### CODE REVIEW

**Comment by ngerritsen** [comment]
There are still some problems with the code. It does not pass the linting, and it has some errors runtime. The first things I can find is that `all` is not defined in `calculateAveragesOf` and the `calculateAverageOf` function does not exist anymore. To be honest I also found the code pretty complex to read. If these could be fixed and the code could be a little bit simpler that would be nice. As for running the app I could send you a key to run it with fontawesome pro.

**Comment by Jobarion** [comment]
If I can run and test the project locally, I can fix those issues. So having the fontawesome key would certainly help :) You can send the key to `throwaway+fpQDgneA@joba.me`

Regarding the complexity of the algorithm, I can try to find a way to simplify it a bit, but it does have some inherent complexity that is probably impossible to simplify completely. I'll try to explain it a little more in a comment.

**Comment by Jobarion** [comment]
I have updated the code, it works fine for me locally. `movingAverageTrimmed` is still quite complex, so if there is anything that is still unclear, let me know and I'll try to clarify it a bit more in the code.

**Review by ngerritsen — APPROVED** [review]
Can you check if the linting passes? With `npm run test`

**Comment by Jobarion** [comment]
Linting passes for me

**Pull request merged**
