### PR TITLE
Improve performance of moving average calculation

### PR DESCRIPTION
**Pull request by Jobarion**
I am unable to get the project to run locally, so this code is only tested out of context. Also note that I'm not really too familiar with JavaScript in general.

### CODE REVIEW

**Comment by ngerritsen** [comment]
> I am unable to get the project to run locally, so this code is only tested out of context. Also note that I'm not really too familiar with JavaScript in general.

Oh that is weird, it should just be an `npm install` and then an `npm run watch` if you have node installed.

**Comment by Jobarion** [comment]
I'll try again later today. I wasn't sure if it was easily possible to get this to run locally, so I didn't invest too much time into this. I'm not a JavaScript dev, so I'm a little inexperienced :)

**Comment by ngerritsen** [comment]
> I'll try again later today. I wasn't sure if it was easily possible to get this to run locally, so I didn't invest too much time into this. I'm not a JavaScript dev, so I'm a little inexperienced :)

Ah wait, you might have issues with the install because I'm using the paid version of fontawesome.

**Comment by Jobarion** [comment]
Yes, that seems to be it. Is there anything I can do to work around that?

**Comment by ngerritsen** [comment]
> Yes, that seems to be it. Is there anything I can do to work around that?

Hmm, not really an easy way. If you rebase I can pull your branch and check it.

**Pull request closed without merging**
